-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here

-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = { "python" },
--   callback = function()
--     vim.cmd('iabbr ifmain if __name__ == "__main__":<Enter>main()<Left>')
--     vim.cmd("iabbr frang for i in range():<Enter><Esc>F(i")
--     -- Other Python abbreviations
--   end,
-- })
