-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here

-- vim.opt.number = false
-- vim.opt.relativenumber = false
--

-- -- 设置光标样式
-- vim.opt.guicursor = {
--   "n-v-c:block-blinkwait700-blinkoff400-blinkon250",
--   "i-ci-ve:ver25-blinkwait700-blinkoff400-blinkon250",
--   "r-cr-o:hor20-blinkwait700-blinkoff400-blinkon250",
-- }
--
-- -- 确保在 tmux 中也能正常工作
-- vim.opt.termguicolors = true
--
-- -- 可选：设置不同模式下的光标颜色
-- vim.cmd([[
--   highlight Cursor guifg=white guibg=black
--   highlight iCursor guifg=white guibg=steelblue
-- ]])
